/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/_index'
import { Route as IndexIndexImport } from './routes/_index/index'
import { Route as IndexUploadImport } from './routes/_index/upload'
import { Route as IndexGenerateIlvImport } from './routes/_index/generate-ilv'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/_index',
  getParentRoute: () => rootRoute,
} as any)

const IndexIndexRoute = IndexIndexImport.update({
  path: '/',
  getParentRoute: () => IndexRoute,
} as any)

const IndexUploadRoute = IndexUploadImport.update({
  path: '/upload',
  getParentRoute: () => IndexRoute,
} as any)

const IndexGenerateIlvRoute = IndexGenerateIlvImport.update({
  path: '/generate-ilv',
  getParentRoute: () => IndexRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_index': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_index/generate-ilv': {
      preLoaderRoute: typeof IndexGenerateIlvImport
      parentRoute: typeof IndexImport
    }
    '/_index/upload': {
      preLoaderRoute: typeof IndexUploadImport
      parentRoute: typeof IndexImport
    }
    '/_index/': {
      preLoaderRoute: typeof IndexIndexImport
      parentRoute: typeof IndexImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute.addChildren([
    IndexGenerateIlvRoute,
    IndexUploadRoute,
    IndexIndexRoute,
  ]),
  LoginRoute,
])

/* prettier-ignore-end */
